### ISSUE TITLE
Team 8 Review - VnV Report - Readability of Outlined Tests

### ISSUE THREAD

**Issue by ShrillP** [MichaelBreau/nlp-mentalhealth#195]
As I was going through your VnV report, I found it difficult to understand what each test was testing exactly from its name. While I was able to understand the tests themselves and what they were accomplishing, when I started to read a test from its name onwards, I found myself a bit confused at the start and I had to try and infer myself based on the test details what that test was trying to do. I think the test names should be made more descriptive by writing the full-form of the acronyms used in the test names (especially the highlighted portion in the below image). 

![image](https://github.com/MichaelBreau/nlp-mentalhealth/assets/36174319/3e558e19-041f-4503-a159-7695179dff2b)

Team 8 TA: @Lyuyang0130

**Comment by MatthewCurtis4** [comment]
We do understand how it may be slightly confusing but it would be unnecessary in our opinion to write Function Requirement Test since it is clearly under the functional requirements evaluation section (same goes for non function requirements). However we do understand the confusion and as a result decided to add FRT and NFRT to the symbols, abbreviations and acronyms sections!
