### ISSUE TITLE
Reinvite me to the repo?

### ISSUE THREAD

**Issue by CSchank** [MichaelBreau/nlp-mentalhealth#64]
Sorry, it seems I let the invitation expire, any chance you could reinvite me to the repo? I might not need it since it's a public repo, but better safe than sorry. Thanks!

**Comment by MichaelBreau** [comment]
P {margin-top:0;margin-bottom:0;} 



Done.




Michael


From: Christopher William Schankula ***@***.***>
Sent: Tuesday, October 10, 2023 4:48 PM
To: MichaelBreau/nlp-mentalhealth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MichaelBreau/nlp-mentalhealth] Reinvite me to the repo? (Issue #64)
 







Caution:
External email. 







Sorry, it seems I let the invitation expire, any chance you could reinvite me to the repo? I might not need it since it's a public repo, but better safe than sorry. Thanks!
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you are subscribed to this thread.Message
 ID: ***@***.***>

**Comment by CSchank** [comment]
Thanks!
