### ISSUE TITLE
Team 8 Review - SR1/SR2 overlap and maybe out of scope for NLP model "hazards"

### ISSUE THREAD

**Issue by MohamedAly8** [MichaelBreau/nlp-mentalhealth#82]
![Screenshot 2023-10-23 at 7 28 30 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/69180195/32bd5b7e-7921-4946-9939-df728819c477)

SR2 makes sense (apart from the grammar error crossed out), but in what other way can a NLP model share information outside by the system if it is bounded by a framework apart from its output. 

SR2 mentions not having user data in the model output, while SR1 says no sensitive data is being shared. I believe that there is a lot of overlap between the two requirements and it can be reduced down to only SR2.

**Comment by MatthewCurtis4** [comment]
SR1 focuses on sharing data outside of this system, such as online or with third-party sites like chat-opt as well. We changed the wording to make this more clear but we feel like both requirements are necessary and separate since SR2 is talking about anonymity in the output file vs sharing/exposing data with other systems and third-parties.
